// Trends/AI 랜딩 레이아웃을 미리 볼 수 있도록 채운 더미 콘텐츠.
// 해당 카테고리에 실제 글이 1건이라도 발행되면 자동으로 사라지고 실제 데이터로 대체됨
// (app/insights/_components/TrendLandingPage.tsx, AiLandingPage.tsx 참고).
import type { HomeArticle } from "@/app/components/home/types";

export const TREND_FALLBACK_ARTICLES: HomeArticle[] = [
  {
    id: -301,
    title: "2026년 하반기, PM이 주목해야 할 프로덕트 트렌드 5가지",
    content:
      "고객 경험 자동화, 데이터 기반 의사결정, 조직 간 협업 방식의 변화까지 — 올해 하반기 PM/PO가 놓치지 말아야 할 흐름을 정리했습니다.",
    category: "trend",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-06T09:00:00.000Z",
  },
  {
    id: -302,
    title: "구독 모델에서 사용량 기반 과금으로, 왜 옮겨가는가",
    content: "SaaS 업계 전반에서 나타나는 과금 모델 전환의 배경과 프로덕트 설계에 주는 시사점을 살펴봅니다.",
    category: "trend",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-05T09:00:00.000Z",
  },
  {
    id: -303,
    title: "국내 PM 채용 시장, 올해는 무엇이 달라졌나",
    content: "채용 공고 데이터로 본 PM 직무의 요구 역량 변화와 주니어 PM이 준비해야 할 것들.",
    category: "trend",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-04T09:00:00.000Z",
  },
  {
    id: -304,
    title: "리테일 앱들이 다시 커뮤니티 기능에 투자하는 이유",
    content: "이커머스 프로덕트 안에서 커뮤니티가 리텐션 지표에 미치는 영향을 사례 중심으로 짚어봅니다.",
    category: "trend",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-03T09:00:00.000Z",
  },
  {
    id: -305,
    title: "숏폼 콘텐츠 다음은 무엇일까 — 다음 세대 인터랙션 예측",
    content: "짧고 빠른 소비 패턴 이후 등장할 새로운 콘텐츠 상호작용 방식에 대한 전망.",
    category: "trend",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-02T09:00:00.000Z",
  },
  {
    id: -306,
    title: "B2B SaaS 온보딩, 5초 안에 승부가 난다",
    content: "가입 직후 이탈을 줄이는 온보딩 설계 원칙을 실제 프로덕트 사례와 함께 소개합니다.",
    category: "trend",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-01T09:00:00.000Z",
  },
  {
    id: -307,
    title: "프로덕트 조직의 리모트 협업, 무엇이 남고 무엇이 사라졌나",
    content: "재택·하이브리드 근무가 정착된 이후 프로덕트팀의 협업 방식이 어떻게 재편되고 있는지 살펴봅니다.",
    category: "trend",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-07-31T09:00:00.000Z",
  },
];

export const AI_FALLBACK_ARTICLES: HomeArticle[] = [
  {
    id: -401,
    title: "AI를 도구로 쓰는 PM과 AI에 끌려다니는 PM의 차이",
    content:
      "AI가 만들어낸 초안과 데이터를 그대로 따르는 대신, 제품의 맥락을 판단 기준으로 삼는 실무 원칙을 정리했습니다.",
    category: "ai",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-06T09:00:00.000Z",
  },
  {
    id: -402,
    title: "LLM 기능을 프로덕트에 붙이기 전에 확인해야 할 것들",
    content: "환각, 응답 지연, 비용 구조까지 — AI 기능을 출시하기 전 PM이 점검해야 할 체크리스트.",
    category: "ai",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-05T09:00:00.000Z",
  },
  {
    id: -403,
    title: "AI 카피라이팅 도구, 실제로 전환율을 올렸을까",
    content: "여러 프로덕트 팀의 AI 카피 도입 사례를 비교해 실제 성과와 한계를 짚어봅니다.",
    category: "ai",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-04T09:00:00.000Z",
  },
  {
    id: -404,
    title: "사내 AI 챗봇 도입, 절반은 왜 실패할까",
    content: "도입은 쉽지만 정착은 어려운 사내 AI 도구, 실패 사례에서 발견한 공통 패턴.",
    category: "ai",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-03T09:00:00.000Z",
  },
  {
    id: -405,
    title: "프롬프트 엔지니어링, PM이 얼마나 알아야 할까",
    content: "개발자만의 영역이라 여겨지던 프롬프트 설계가 왜 PM의 역량이 되어가고 있는지 살펴봅니다.",
    category: "ai",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-02T09:00:00.000Z",
  },
  {
    id: -406,
    title: "AI 에이전트 시대, 프로덕트 설계는 무엇이 달라지나",
    content: "사람이 아니라 에이전트가 사용자가 되는 상황을 가정한 인터페이스 설계 원칙을 정리했습니다.",
    category: "ai",
    author: "The PMPO",
    author_id: "fallback",
    image_url: null,
    created_at: "2026-08-01T09:00:00.000Z",
  },
];
