-- 댓글 기능 (화면설계 화면2 기준)
-- 1depth 고정, 대댓글/공유 없음 (PRD Out of Scope)
-- 읽기는 비로그인 포함 누구나 가능, 작성/삭제는 로그인 + 본인 댓글만 (posts와 동일 규칙)

create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  user_id text not null,
  author text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table comments enable row level security;

drop policy if exists "comments are publicly readable" on comments;
create policy "comments are publicly readable"
  on comments for select
  using (true);

drop policy if exists "users can insert their own comments" on comments;
create policy "users can insert their own comments"
  on comments for insert
  with check (auth.uid()::text = user_id);

drop policy if exists "users can delete their own comments" on comments;
create policy "users can delete their own comments"
  on comments for delete
  using (auth.uid()::text = user_id);
