-- 좋아요 기능 (화면설계 화면2 기준)
-- 게시글/댓글 공용 likes 테이블. 클릭 시 +1, 재클릭 시 취소(row 삭제)
-- 로그인 필요, 읽기(카운트 노출)는 비로그인 포함 누구나 가능

create table if not exists likes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  post_id bigint references posts(id) on delete cascade,
  comment_id bigint references comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint likes_target_check check (
    (post_id is not null and comment_id is null) or
    (post_id is null and comment_id is not null)
  )
);

-- 같은 유저가 같은 글/댓글에 중복으로 좋아요를 남기지 못하도록 부분 유니크 인덱스 설정
create unique index if not exists likes_unique_post_like
  on likes (user_id, post_id) where post_id is not null;

create unique index if not exists likes_unique_comment_like
  on likes (user_id, comment_id) where comment_id is not null;

alter table likes enable row level security;

drop policy if exists "likes are publicly readable" on likes;
create policy "likes are publicly readable"
  on likes for select
  using (true);

drop policy if exists "users can insert their own likes" on likes;
create policy "users can insert their own likes"
  on likes for insert
  with check (auth.uid()::text = user_id);

drop policy if exists "users can delete their own likes" on likes;
create policy "users can delete their own likes"
  on likes for delete
  using (auth.uid()::text = user_id);
