-- 팔로우 기능 (PRD Must-have 3-2, 5 / 화면설계 화면8, 10 기준)
-- 팔로우 30명 이상 시 뱃지 자동 부여는 프론트에서 팔로워 수로 판정 (별도 컬럼 없음)

create table if not exists follows (
  id bigint generated by default as identity primary key,
  follower_id text not null,
  following_id text not null,
  created_at timestamptz not null default now(),
  constraint follows_no_self_follow check (follower_id <> following_id)
);

create unique index if not exists follows_unique_pair
  on follows (follower_id, following_id);

alter table follows enable row level security;

drop policy if exists "follows are publicly readable" on follows;
create policy "follows are publicly readable"
  on follows for select
  using (true);

drop policy if exists "users can insert their own follows" on follows;
create policy "users can insert their own follows"
  on follows for insert
  with check (auth.uid()::text = follower_id);

drop policy if exists "users can delete their own follows" on follows;
create policy "users can delete their own follows"
  on follows for delete
  using (auth.uid()::text = follower_id);
