-- 정보게시판 기능 (PRD Must-have 2 / 화면설계 화면3·4)
-- 작성은 관리자만 가능, 좋아요/댓글은 커뮤니티와 동일 규칙으로 유저에게 허용 (1depth, 대댓글/공유 없음)
-- comments/likes 테이블은 커뮤니티(posts)와 동일 규칙을 공유해야 하므로 article_id 컬럼을 추가해 재사용

-- 1. 관리자 판별 플래그
alter table profiles
  add column if not exists is_admin boolean not null default false;

-- 2. articles: 관리자 발행 정보게시판 글
create table if not exists articles (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null check (category in ('product', 'trend', 'ai')),
  author_id uuid not null references auth.users(id),
  author text not null,
  image_url text,
  created_at timestamptz not null default now()
);

alter table articles enable row level security;

drop policy if exists "articles are publicly readable" on articles;
create policy "articles are publicly readable"
  on articles for select
  using (true);

drop policy if exists "only admins can insert articles" on articles;
create policy "only admins can insert articles"
  on articles for insert
  with check (
    auth.uid() = author_id
    and exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  );

drop policy if exists "only admins can update their articles" on articles;
create policy "only admins can update their articles"
  on articles for update
  using (
    auth.uid() = author_id
    and exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  );

drop policy if exists "only admins can delete their articles" on articles;
create policy "only admins can delete their articles"
  on articles for delete
  using (
    auth.uid() = author_id
    and exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  );

-- 3. comments 테이블에 article_id 추가 (post_id와 배타적으로 하나만 채워짐)
alter table comments
  add column if not exists article_id bigint references articles(id) on delete cascade;

alter table comments
  alter column post_id drop not null;

alter table comments
  drop constraint if exists comments_target_check;

alter table comments
  add constraint comments_target_check check (
    (post_id is not null and article_id is null) or
    (post_id is null and article_id is not null)
  );

-- 4. likes 테이블에 article_id 추가 (post_id/comment_id/article_id 중 하나만 채워짐)
alter table likes
  add column if not exists article_id bigint references articles(id) on delete cascade;

alter table likes
  drop constraint if exists likes_target_check;

alter table likes
  add constraint likes_target_check check (
    (post_id is not null and comment_id is null and article_id is null) or
    (post_id is null and comment_id is not null and article_id is null) or
    (post_id is null and comment_id is null and article_id is not null)
  );

create unique index if not exists likes_unique_article_like
  on likes (user_id, article_id) where article_id is not null;
