-- 정보게시판 조회수 (화면설계 화면4)
-- 로그인 유저는 user_id, 비로그인은 브라우저 익명 쿠키 기준으로 24시간 내 중복 조회는 카운트 제외
-- 조회 로그를 그대로 쌓고, 노출용 조회수는 article_id별 로그 개수로 계산

create table if not exists article_views (
  id bigint generated by default as identity primary key,
  article_id bigint not null references articles(id) on delete cascade,
  viewer_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists article_views_article_id_idx on article_views (article_id);
create index if not exists article_views_dedupe_idx on article_views (article_id, viewer_key, created_at);

alter table article_views enable row level security;

drop policy if exists "article views are publicly readable" on article_views;
create policy "article views are publicly readable"
  on article_views for select
  using (true);

drop policy if exists "anyone can log an article view" on article_views;
create policy "anyone can log an article view"
  on article_views for insert
  with check (true);
