-- 신고/차단/키워드 필터 등 리스크 대응 기능
-- PRD "리스크 및 대응": 유저 신고 기능 / 관리자의 유저 게시글·댓글 작성 블락 기능 / 키워드 확인 후 차단 기능
--
-- 구성:
-- 1. profiles.is_blocked (관리자만 변경 가능하도록 트리거로 보호, 0010의 is_admin 셀프승격 방지 패턴과 동일)
-- 2. set_user_blocked() — 관리자가 특정 유저를 차단/해제하는 RPC (SECURITY DEFINER, 0012의 delete_own_account 패턴)
-- 3. reports — 게시글/댓글 신고 (유저는 본인 신고만 등록, 조회/삭제는 관리자만)
-- 4. banned_keywords — 금지 키워드 목록 (조회는 누구나(클라이언트 사전 검증용), 쓰기는 관리자만)
-- 5. posts/comments에 BEFORE INSERT 트리거로 서버단 강제 — 차단된 유저의 작성 차단 + 금지 키워드 포함 시 차단
--    (클라이언트 검증만으로는 REST API 직접 호출을 막을 수 없으므로 DB 트리거로 실제 방어선을 둠)
--    주의: posts는 title만 있고 content 컬럼이 없음(articles/comments와 다름) — 트리거도 이에 맞춰 분리

-- 1. profiles.is_blocked
alter table profiles
  add column if not exists is_blocked boolean not null default false;

create or replace function prevent_client_is_blocked_change()
returns trigger as $$
begin
  if new.is_blocked is distinct from old.is_blocked then
    if auth.role() in ('authenticated', 'anon') then
      raise exception 'is_blocked은 클라이언트 요청으로 변경할 수 없습니다';
    end if;
  end if;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists prevent_client_is_blocked_change on profiles;
create trigger prevent_client_is_blocked_change
  before update on profiles
  for each row execute function prevent_client_is_blocked_change();

-- 2. 관리자용 차단/해제 RPC
create or replace function set_user_blocked(target_user_id uuid, blocked boolean)
returns void as $$
begin
  if not exists (select 1 from profiles where id = auth.uid() and is_admin = true) then
    raise exception '관리자만 사용할 수 있습니다';
  end if;

  if target_user_id = auth.uid() then
    raise exception '본인 계정은 차단할 수 없습니다';
  end if;

  update profiles set is_blocked = blocked where id = target_user_id;
end;
$$ language plpgsql security definer set search_path = public, auth;

grant execute on function set_user_blocked(uuid, boolean) to authenticated;

-- 3. 신고 (게시글/댓글/정보게시판 아티클 공용 — comments/likes와 동일하게 post_id/comment_id/article_id 중 하나만 채워짐)
create table if not exists reports (
  id bigint generated by default as identity primary key,
  reporter_id text not null,
  post_id bigint references posts(id) on delete cascade,
  comment_id bigint references comments(id) on delete cascade,
  article_id bigint references articles(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now()
);

alter table reports
  add column if not exists article_id bigint references articles(id) on delete cascade;

alter table reports
  drop constraint if exists reports_target_check;
alter table reports
  add constraint reports_target_check check (
    (post_id is not null and comment_id is null and article_id is null) or
    (post_id is null and comment_id is not null and article_id is null) or
    (post_id is null and comment_id is null and article_id is not null)
  );

create unique index if not exists reports_unique_post_report
  on reports (reporter_id, post_id) where post_id is not null;
create unique index if not exists reports_unique_comment_report
  on reports (reporter_id, comment_id) where comment_id is not null;
create unique index if not exists reports_unique_article_report
  on reports (reporter_id, article_id) where article_id is not null;

alter table reports enable row level security;

drop policy if exists "users can insert their own reports" on reports;
create policy "users can insert their own reports"
  on reports for insert
  with check (auth.uid()::text = reporter_id);

drop policy if exists "only admins can view reports" on reports;
create policy "only admins can view reports"
  on reports for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "only admins can delete reports" on reports;
create policy "only admins can delete reports"
  on reports for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- 4. 금지 키워드
create table if not exists banned_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  created_at timestamptz not null default now()
);

alter table banned_keywords enable row level security;

drop policy if exists "banned keywords are publicly readable" on banned_keywords;
create policy "banned keywords are publicly readable"
  on banned_keywords for select
  using (true);

drop policy if exists "only admins can insert banned keywords" on banned_keywords;
create policy "only admins can insert banned keywords"
  on banned_keywords for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "only admins can delete banned keywords" on banned_keywords;
create policy "only admins can delete banned keywords"
  on banned_keywords for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- 4-1. 관리자가 신고된 게시글/댓글을 직접 삭제할 수 있도록 허용
--      (기존 "본인 글만 삭제 가능" 정책은 그대로 두고, 관리자용 정책을 추가 — RLS는 같은 종류 정책을 OR로 합침)
drop policy if exists "admins can delete any post" on posts;
create policy "admins can delete any post"
  on posts for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can delete any comment" on comments;
create policy "admins can delete any comment"
  on comments for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- 5. posts/comments 작성 시 서버단 강제 (차단된 유저 + 금지 키워드)
create or replace function enforce_post_moderation()
returns trigger as $$
begin
  if exists (select 1 from profiles where id::text = new.user_id and is_blocked = true) then
    raise exception '차단된 계정은 글을 작성할 수 없습니다';
  end if;

  if exists (select 1 from banned_keywords where new.title ilike '%' || keyword || '%') then
    raise exception '금지된 단어가 포함되어 있습니다';
  end if;

  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists enforce_post_moderation on posts;
create trigger enforce_post_moderation
  before insert on posts
  for each row execute function enforce_post_moderation();

create or replace function enforce_comment_moderation()
returns trigger as $$
begin
  if exists (select 1 from profiles where id::text = new.user_id and is_blocked = true) then
    raise exception '차단된 계정은 댓글을 작성할 수 없습니다';
  end if;

  if exists (select 1 from banned_keywords where new.content ilike '%' || keyword || '%') then
    raise exception '금지된 단어가 포함되어 있습니다';
  end if;

  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists enforce_comment_moderation on comments;
create trigger enforce_comment_moderation
  before insert on comments
  for each row execute function enforce_comment_moderation();
