-- Product(서비스 디렉토리) 기능. articles(제목/본문 장문 구조)와는 데이터 모양이 달라
-- 별도 테이블로 분리 — 카드 하나 = 서비스 하나(이미지/이름/소개/대표링크) + 플랫폼별 링크 N개.
-- category는 지금은 필터 UI 없이 자유 입력 텍스트로만 저장, 나중에 필터 기능 추가할 때 그대로 사용.

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  image_url text not null,
  primary_link text not null,
  category text,
  author_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists product_platforms (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  platform text not null check (platform in ('app_store', 'google_play', 'web', 'etc')),
  url text not null
);

alter table products enable row level security;
alter table product_platforms enable row level security;

-- 읽기: nav_menu_settings.product가 public이거나, 요청자가 관리자면 허용.
-- Product 메뉴를 "관리자만 공개"로 켜둔 지금 상태에서는 일반 유저/비로그인 요청은
-- API를 직접 호출해도 이 조건에서 걸러짐 (화면단 숨김과 별개로 서버단에서 실제로 차단됨).
drop policy if exists "public or admin can view products" on products;
create policy "public or admin can view products"
  on products for select
  using (
    exists (select 1 from nav_menu_settings where key = 'product' and visibility = 'public')
    or exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  );

drop policy if exists "public or admin can view product platforms" on product_platforms;
create policy "public or admin can view product platforms"
  on product_platforms for select
  using (
    exists (select 1 from nav_menu_settings where key = 'product' and visibility = 'public')
    or exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  );

drop policy if exists "admins can insert products" on products;
create policy "admins can insert products"
  on products for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can update products" on products;
create policy "admins can update products"
  on products for update
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can delete products" on products;
create policy "admins can delete products"
  on products for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can insert product platforms" on product_platforms;
create policy "admins can insert product platforms"
  on product_platforms for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can update product platforms" on product_platforms;
create policy "admins can update product platforms"
  on product_platforms for update
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can delete product platforms" on product_platforms;
create policy "admins can delete product platforms"
  on product_platforms for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
