-- Trends/AI 세부 카테고리(태그) 시스템.
-- 대분류(articles.category)와 별개의 추가 레이어 — Product는 별도 테이블(products)이라 무관.
-- 세부 카테고리는 category별로 완전히 독립(unique 제약 + 모든 조회가 category로 필터링되므로
-- Trends 세부 카테고리가 AI 쪽 드롭다운/필터에 섞일 수 없음).

create table if not exists article_subcategories (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('trend', 'ai')),
  name text not null,
  created_at timestamptz not null default now(),
  unique (category, name)
);

alter table articles
  add column if not exists subcategory_id bigint references article_subcategories(id);

alter table article_subcategories enable row level security;

drop policy if exists "anyone can view article subcategories" on article_subcategories;
create policy "anyone can view article subcategories"
  on article_subcategories for select
  using (true);

drop policy if exists "admins can insert article subcategories" on article_subcategories;
create policy "admins can insert article subcategories"
  on article_subcategories for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
