-- Product(서비스 디렉토리) 전용 2단 카테고리 시스템 신규 구축.
-- 기존 products.category(자유 텍스트, 필터 UI 없이 방치돼 있던 컬럼)를 대체하는 용도 —
-- 컬럼 자체는 하위 호환을 위해 그대로 두고 새 관계형 컬럼만 추가함.

create table if not exists product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists product_subcategories (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint not null references product_categories(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (category_id, name)
);

alter table products
  add column if not exists category_id bigint references product_categories(id) on delete set null;
alter table products
  add column if not exists subcategory_id bigint references product_subcategories(id) on delete set null;

alter table product_categories enable row level security;
alter table product_subcategories enable row level security;

drop policy if exists "anyone can view product categories" on product_categories;
create policy "anyone can view product categories"
  on product_categories for select
  using (true);

drop policy if exists "admins can insert product categories" on product_categories;
create policy "admins can insert product categories"
  on product_categories for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can delete product categories" on product_categories;
create policy "admins can delete product categories"
  on product_categories for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "anyone can view product subcategories" on product_subcategories;
create policy "anyone can view product subcategories"
  on product_subcategories for select
  using (true);

drop policy if exists "admins can insert product subcategories" on product_subcategories;
create policy "admins can insert product subcategories"
  on product_subcategories for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

drop policy if exists "admins can delete product subcategories" on product_subcategories;
create policy "admins can delete product subcategories"
  on product_subcategories for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
